### ISSUE TITLE
Plugin doesn't work in IE9

### ISSUE THREAD

**Issue by rafagarcia** [adeelejaz/jquery-image-resize#6] opened 2011-05-14 11:33 UTC
Hi. After implementing it and watching it working in Firefox and Chrome, what was my surprise when i loaded my page (http://www.universoweb.com/jordiescandell/fotografia.php?idimagen=130) in IE9 and realised that the plugin doesn´t work in this browser. Then checked your jsfiddle version and it doesn´t work either (http://jsfiddle.net/CpFDm/). Checking the code in firebug and ie9 developer tool it seems that, in IE, the image doesn´t print the new height and width values "on the fly". Hope you can find a solution because the plugin works fine in firefox and chrome. Thanks in advance.

**Comment by adeelejaz** [comment] 2011-05-25 00:41
I cannot access your version of the script as it is asking for a username and password. The jsfiddle version gives an error (something to do with the type returned by github when asking for the js file). I have uploaded the sample code on my own server: http://adeelejaz.com/projects/jquery/imageresize/example.html It works fine in IE9. Can you please check and verify?

**Comment by greddin** [comment] 2011-08-09 01:05
I can confirm that the http://jsfiddle.net/CpFDm and the http://adeelejaz.com/projects/jquery/imageresize/example.html links do not work in IE9 for me. 

With the exception of not working in IE9, this plugin is without doubt the best and easiest to use and implement. Please see if you can fix the IE9 issue.

**Comment by adeelejaz** [comment] 2011-08-10 11:15
Thanks for reporting this.. I think I know what this might be.. I'll post back with the fix soon..

**Comment by adeelejaz** [comment] 2011-08-11 20:56
As it turns out, it isn't anything to do with the what I thought. It seems <del>jsfiddle and github cannot really work together</del> <ins>IE9 has issues because github returns the .js file with the header of text/plain</ins>. I added the plugin js link from my server and it works now: http://jsfiddle.net/CpFDm/15/

Can you please confirm this is working for you now so I can close this?

**Comment by greddin** [comment] 2011-08-11 21:55
I can confirm that the example on the http://jsfiddle.net/CpFDm/15/ does work now in IE9. But with that said, the example.html that is packaged in the 2.1.1 source download still do not work in IE9.

**Comment by adeelejaz** [comment] 2011-08-11 22:01
I think we are getting somewhere.. Can you please confirm if refreshing example.html by pressing F5 makes the images resize?

**Comment by greddin** [comment] 2011-08-11 22:09
Yes. Refreshing the example.html by pressing F5 does indeed make the images resize.

**Comment by adeelejaz** [comment] 2011-08-11 22:25
I've uploaded the same files on my server and IE9 behaves properly. I think its the ActiveX Filter notification that is causing the problem. When you run the file locally, it stops the JavaScript from executing and when you enable the filter, it still doesn't run it.

**Comment by greddin** [comment] 2011-08-11 23:05
I've uploaded the 2.1.1 sample files to my server now. But the same behavior exists. On initial page load, the images are full size, but pressing F5 forces them to resize correctly. 

Try closing all your browsers to ensure a fresh session and go here:
http://greddin.com/jquery/example.html

**Comment by rstotland** [comment] 2011-10-26 01:53
Hey guys, I get the same problem with IE9 here, as far as refreshing I noticed that actually it only works some times. Even on greddins example page. If you keep refreshing it will load sometime and other times the images are all the same size as their originals. Really hope there is a fix soon as this is a great plugin :) Thanks!

**Comment by adeelejaz** [comment] 2012-05-18 15:04
I know this has been long coming, but its finally fixed.

**Closed as completed by adeelejaz** 2012-05-18 15:04 UTC
